### ISSUE TITLE
List all the URLs for Related Services

### ISSUE THREAD

**Issue by Share2Learn2** [robatipoor/rustfulapi#16]
It shall be helpful to list all the integrated services, URL , description etc

**Comment by robatipoor** [comment]
Do you think that Swagger UI is not enough? For Swagger panel, just open http://127.0.0.1:8080/swagger-ui/ in a browser.

**Comment by Share2Learn2** [comment]
i meant about background services such as mailhog pgadmin etc 
your code deliver that 
but that is not represented in the read me etc
